config/routes.rb
StackClone::Application.routes.draw do

  root :to => "main#landing"

  resources :events

  resources :comments , :only => [:create, :update, :destroy]
  resources :votes , :only => [:create, :update, :destroy]

  match 'session/auth', to: 'sessions#auth'

  match '/sign_in', to: 'sessions#sign_in'
  match '/sign_out', to: 'sessions#sign_out'

  match '/rsvp', to: 'rsvps#rsvp'

end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  attr_accessible :text, :author, :author_id, :parent, :parent_id, :event, :event_id
  
  validates :text, :presence => true

  belongs_to :parent, :class_name => "Comment"
  belongs_to :event
  belongs_to :author, :class_name => "User"
  has_many :replies, :class_name => "Comment", :foreign_key => :parent_id
  has_many :votes
  belongs_to :parent, :class_name => "Comment"

  def votes_sum
    votes.inject(0) {|acc, v| acc += v.value}
  end

  def vote_by(user) 
    Vote.where(comment_id: self.id, voter_id: user.id).first
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  require 'carrierwave/orm/activerecord'

  attr_accessible :title, :start, :photo_file, :description, :organizer, :organizer_id, :end

  validates :title, :presence => true
  validates :start, :presence => true
  validates :description, :presence => true

  belongs_to :organizer, :class_name => "User"
  has_many :attendees
  has_many :participants, :through => :attendees, :source => :user
  has_many :event_tags
  has_many :tags, :through => :event_tags
  has_many :comments

  mount_uploader :photo_file, PhotoUploader


end

app/models/event_tag.rb
class EventTag < ActiveRecord::Base

  belongs_to :tag
  belongs_to :event

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  validates :name, :presence => true
  validates :name, :uniqueness => true

  has_many :event_tags
  has_many :events, :through => :event_tags

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :oauth_token, :oauth_secret, :id, :twitter_handle
  
  has_many :created_events, :class_name => "Event", :foreign_key => :organizer_id
  has_many :attendees
  has_many :attended_events, :through => :attendees, :source => :event
  has_many :votes, :foreign_key => :voter_id
  has_many :comments, :foreign_key => :author_id
  has_many :voted_on_comments, :through => :votes, :source => :comment


  def twitter_client
    @twitter_client ||= Twitter::Client.new(:oauth_token => oauth_token,
                                            :oauth_token_secret => oauth_secret)
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :value, :comment, :comment_id, :voter, :voter_id
  validates_uniqueness_of :voter_id, :scope => :comment_id

  belongs_to :comment
  belongs_to :voter, :class_name => "User"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :require_login

  def require_login
    redirect_to '/' unless current_user
  end

  def current_user
    User.find_by_id(session[:user_id])
  end
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_filter :user_created_comment, only: [:update, :destroy]

  def user_created_comment
    @comment = current_user.comments.find_by_id(params[:id])
    redirect_to '/' unless @comment
  end

  def create
    @comment = Comment.new(params[:comment])
    current_user.comments << @comment
    if request.xhr?
      @comment = @comment.parent if @comment.parent
      render partial: "events/show_comment"
    else
      redirect_to (session[:return_to] || '/')
    end
  end

  def update
    @comment.update_attributes(params[:comment])

    if request.xhr?
      render partial: "events/show_comment"
    else
      redirect_to (session[:return_to] || '/')
    end
  end

  def destroy
    id = @comment.id
    @comment.destroy
    if request.xhr?
      render text: id
    else
      redirect_to (session[:return_to] || '/')
    end
  end
  
end

app/controllers/event_tags_controller.rb
class EventTagsController < ApplicationController
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_filter :require_login, only: [:index, :show]
  before_filter :user_created_event, only: [:edit, :update, :destroy]

  def user_created_event
    @event = current_user.created_events.find_by_id(params[:id])
    redirect_to '/' unless @event
  end

  def index
    #@events = Event.all
    @events = Event.order("start").limit(20)
  end

  def new
    @event = Event.new
  end

  def create
    current_user.created_events << Event.new(params[:event])
    redirect_to events_path
  end

  def show
    @event = Event.find(params[:id])
    session[:return_to] = event_path(@event)
  end

  def edit
  end

  def update
    @event.update_attributes(params[:event])
    redirect_to event_path(@event)
  end

  def destroy
    @event.destroy
    redirect_to events_path
  end
  
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  skip_before_filter :require_login

  def landing
    @user = User.find_by_id(session[:user_id])
    render :layout => "landing"
  end
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController

  def rsvp
    @event = Event.find(params[:id])
    current_user.attended_events << @event
    render partial: "sidebars/show_rsvp_attending"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :require_login
  
  def sign_in
    redirect_to request_token.authorize_url
  end

  def sign_out
    session.clear
    redirect_to '/'
  end

  def auth
    @access_token = request_token.get_access_token(:oauth_verifier => params[:oauth_verifier])
    session.delete(:request_token)
    @user = User.find_by_twitter_handle(@access_token.params[:screen_name])

    if @user
      @user.update_attributes(oauth_token: @access_token.token, oauth_secret: @access_token.secret)
    else
      @user = User.create(oauth_token: @access_token.token, oauth_secret: @access_token.secret, twitter_handle: @access_token.params[:screen_name])
    end

    Rails.logger.debug(@user.inspect)
    session[:user_id] = @user.id

    redirect_to events_path
  end

  private

  def oauth_consumer
    raise RuntimeError, "You must set TWITTER_KEY and TWITTER_SECRET in your server environment." unless ENV['TWITTER_KEY'] and ENV['TWITTER_SECRET']
    @consumer ||= OAuth::Consumer.new(
      ENV['TWITTER_KEY'],
      ENV['TWITTER_SECRET'],
      :site => "https://api.twitter.com"
    )
  end

  def request_token
    if not session[:request_token]
      host_and_port = request.host
      host_and_port << ":3000" if request.host == "localhost" || request.host == "0.0.0.0"
      session[:request_token] = oauth_consumer.get_request_token(
        :oauth_callback => "http://#{host_and_port}/session/auth"
      )
    end
    session[:request_token]
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  before_filter :user_created_votes, only: [:update, :destroy]

  def user_created_votes
    @vote = current_user.votes.find_by_id(params[:id])
    redirect_to '/' unless @vote
  end

  def create
    @vote = Vote.new(params[:vote])
    current_user.votes << @vote
    if request.xhr?
      @comment = @vote.comment
      render partial: "events/votes_forms"
    else
      redirect_to (session[:return_to] || '/')
    end
  end

  def update
    @vote.update_attributes(params[:vote])
    if request.xhr?
      @comment = @vote.comment
      render partial: "events/votes_forms"
    else
      redirect_to (session[:return_to] || '/')
    end
  end

  def destroy
    @comment = @vote.comment
    @vote.destroy
    @vote = nil
    if request.xhr?
      render partial: "events/votes_forms"
    else
      redirect_to (session[:return_to] || '/')
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @user ||= User.find_by_id(session[:user_id])
  end
end

app/views/events/_comment_form.html.erb
<%= form_for Comment.new(parent: @comment), html: {class: "reply hidden"} do |f| %>
  <%= f.hidden_field :parent_id %>

  <%= f.hidden_field :event_id %>
  
  <%= f.text_area :text, class: "comment_textarea" %><br>
  <%= f.submit "Reply", class: "vote_button" %>
<% end %>
  

app/views/events/_form.html.erb
<div class="event_wrapper">
  <%= form_for @event do |f| %>

    <%= label_tag(:title, "Title:") %>
    <%= f.text_field :title, class: "title_input" %>

    <br><br>

    <%= label_tag(:description, "Description:") %>
    <%= f.text_area :description %>

    <br><br>

    <%= label_tag(:start, "Start:") %>
    <%= f.datetime_select :start, 
      ampm: true, 
      minute_step: 5,
      start_year: Time.now.year,
      user_short_month: true,
      order: [:month, :day, :year] %>

    <br>

    <%= label_tag(:end, "End:") %>
    <%= f.datetime_select :end, 
      ampm: true, 
      minute_step: 5,
      start_year: Time.now.year,
      user_short_month: true,
      order: [:month, :day, :year] %>

    <br>
    
    <!--
    <%= label_tag(:photo_file, "Photo:") %>
    <%= f.file_field :photo_file %>
    <br>
    -->

    <br>
    
    <%= f.submit "submit", class: "button" %>

  <% end %>
  <br>
  <p class="small">
    <% if @event.id != nil %>
      <%= link_to "cancel", event_path(@event) %>
    <% else%>
      <%= link_to "cancel", events_path %>
    <% end %>
  </p>

</div>

app/views/events/_show_comment.html.erb
<div class="comments" data-id="<%= @comment.id %>">
  
  <p class="light_gray_text comment_author small">
    <% if @comment.author == current_user %>
      You wrote:
    <% else %>
      <%= link_to "@#{@comment.author.twitter_handle}", "http://twitter.com/#{@comment.author.twitter_handle}" %> wrote:
    <% end %>
  </p>

  <p class="comment_text"><%= @comment.text %></p>
  <%= form_for @comment, html: {class: "edit comment_text hidden"} do |f| %>
     <%= f.hidden_field :parent_id %>
     <%= f.text_area :text, size: "50x4" %><br>
     <%= f.submit "Save Edits" %>
  <% end %>
  <br>

  <% if current_user && current_user.comments.find_by_id(@comment.id) %>
    <p class="light_gray_text small">
      <a class="edit" href="#">edit</a>
      <%= link_to("delete", comment_path(@comment), method: :delete, class: "delete") %>
    </p>
  <% end %>

  <p class="light_gray_text small" id="vote_tally">
    <%= render "events/vote_tally" %>
  </p>

  <div class="votes-forms">
    <%= render "events/votes_forms" %>
  </div>

  <%= form_for @comment, html: {class: "edit text hidden"} do |f| %>
    <%= f.hidden_field :parent_id %>
    <%= f.text_area :text, size: "50x4" %><br>
    <%= f.submit "Edit" %>
  <% end %>

  <br>

  <% if current_user %>
    <a class="reply small" href="#">reply</a>
    <%= render "events/comment_form" %>
  <% end %>

  <div class="nested">
    <% @comment.replies.each do |comment| %>
      <% @comment = comment %>
      <%= render "events/show_comment" %>
    <% end %>
  </div>
</div>

app/views/events/_vote_tally.html.erb
<% if @comment.votes.any? %>
    This comment has <%= @comment.votes.where("value = 1").count %>
    <%= @comment.votes.where("value = 1").count == 1 ? "upvote" : "upvotes" %> and
    <%= @comment.votes.where("value = -1").count %>
    <%= @comment.votes.where("value = -1").count == 1 ? "downvote" : "downvotes" %>.
<% else %>
  No votes have been cast for this comment.
<% end %>

app/views/events/_votes_forms.html.erb
<% if current_user %>
  <% vote = @comment.vote_by(current_user) %>
<% end %>

<% if vote %>

  <p class="light_gray_text small" data-comment-id="<%= @comment.id %>">
    <%= vote.value == 1 ? "You upvoted this comment." : "You downvoted this comment." %>
    <br>
    <%= link_to "withdraw your vote", vote_path(vote), method: :delete, class: "delete-vote" %>
  </p>
  
<% elsif current_user %>

  <div class="vote_forms_wrap" data-comment-id="<%= @comment.id %>">
    <%= form_for Vote.new(comment: @comment, value: 1) do |f|%>
      <%= f.hidden_field :comment_id %>
      <%= f.hidden_field :value %>

      <%= button_tag( :class => "upvote vote_button") do %>
        <i class="icon-arrow-up"></i>
      <% end %>
    <% end %>

    <%= form_for Vote.new(comment: @comment, value: -1) do |f|%>
      <%= f.hidden_field :comment_id %>
      <%= f.hidden_field :value %>
      <%= button_tag( :class => "downvote vote_button") do %>
        <i class="icon-arrow-down"></i>
      <% end %>
    <% end %>
  </div>

<% else %>

  <p class="light_gray_text small"><%= link_to 'sign in to vote or leave a reply', '/sign_in' %></p>

<% end %>

app/views/events/edit.html.erb
<h1><%= @event.title %></h1>

<div id="sidebar">
  <% if current_user %>
    <%= render "sidebars/events_show" %>
  <% else %>
    <%= render "sidebars/no_current_user" %>
  <% end %>
</div>

<div id="events_wrapper">
  <%= render "form" %>
</div>

app/views/events/index.html.erb
<h1>Upcoming Events</h1>

<div id="sidebar">
  <% if current_user %>
    <%= render "sidebars/events_index" %>
  <% else %>
    <%= render "sidebars/no_current_user" %>
  <% end %>
</div>

<div id="events_wrapper">

  <% @events.each do |event| %>

    <div class="event_wrapper">
      <%= link_to event.title, event %><br>
      <p class="event_date left"><%= event.start.strftime("%A, %B %-d at %-l:%M%p") %> by <%= link_to "@#{event.organizer.twitter_handle}", "http://twitter.com/#{event.organizer.twitter_handle}" %></p>
    </div>
    
  <% end %>

</div>

app/views/events/new.html.erb
<h1>Create Your New Event</h1>

<div id="sidebar">
  <% if current_user %>
    <%= render "sidebars/events_index" %>
  <% else %>
    <%= render "sidebars/no_current_user" %>
  <% end %>
</div>

<div id="events_wrapper">
  <%= render "form" %>
</div>

app/views/events/show.html.erb
<h1 data-id="<%= @event.id %>"><%= @event.title %></h1>

<div id="sidebar">
  <% if current_user %>
    <%= render "sidebars/events_show" %>
  <% else %>
    <%= render "sidebars/no_current_user" %>
  <% end %>
</div>

<div id="events_wrapper">

  <div class="event_info">
    <h3>Event Description</h3>
    <p><%= @event.description %></p>

    <ul>
      <% @event.tags.each do |tag| %>
        <li><%= tag.name %></li>
      <% end %>
    </ul>

    <br><br>

    <h3>Event Details</h3>
    <div class="event_details">
      <p>Organizer: <%= link_to "@#{@event.organizer.twitter_handle}", "http://twitter.com/#{@event.organizer.twitter_handle}" %></p>
      <p>Starts: <%= @event.start.strftime("%A, %B %-d at %-l:%M %p") %></p>    
      <p>Ends: <%= @event.end.strftime("%A, %B %-d at %-l:%M %p") if @event.end %></p>
    </div>

    <br><Br>

    <h3>Comments:</h3>

    <% if session[:user_id] %>
      <p>Help craft this event.  Post a suggestion for @<%=@event.organizer.twitter_handle %>.</p>

      <%= form_for Comment.new(event: @event), html: {class: "event_comment"} do |f| %>
        <%= f.hidden_field :event_id %>
        <%= f.text_area :text, size: "50x4" %><br>
        <%= f.submit "Post Comment", class: "button" %>
      <% end %>
    <% end %>

  </div>

  <div class="comments_wrapper">
    <% @event.comments.each do |comment| %>
      <div class="event_wrapper">
        <% @comment = comment %>
        <%= render "show_comment" %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StackClone</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
</head>
<body>

<header>
  <div id="header_content">
    <div class="left pad-right">
      <%= link_to "view events", events_path %>
    </div>
    <div class="left">
      <%= link_to "create event", new_event_path %>
    </div>

    
      <% if session[:user_id] %>
        <div class="right">
          <%= link_to "sign out", "/sign_out" %>
        </div>
        <div class="right pad-right">
          @<%= current_user.twitter_handle %>
        </div>
      <% else %>
        <div class="right">
          <%= link_to "sign in with twitter", "/sign_in" %>
        </div>
      <% end %>
  </div>
</header>

<div id="container">
  <%= yield %>
</div>

</body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Other Clone</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="landing">

<%= yield %>

</body>
</html>

app/views/main/landing.html.erb
<div id=sign_in_wrap>

  <h1>Event Crafting</h1>
  <h3>plan collaboratively with your guests</h3>

  <a href="/sign_in"><div id="sign_in_button">Sign In with Twitter</div></a>

  <p><%= link_to "Or browse events ...", events_path %></p>

</div>

app/views/sidebars/_event_attendees.html.erb
<% @event.participants.each do |participant| %>
  <p><%= link_to "@#{participant.twitter_handle}", "http://twitter.com/#{participant.twitter_handle}" %></p>
<% end %>

app/views/sidebars/_events_index.html.erb
<h3>Your Events</h3>

<% if current_user.created_events.any? %>
  <% current_user.created_events.each do |event| %>
    <p><%= link_to event.title, event_path(event) %></p><br>
  <% end %>
<% else %>
  <p>You have no upcoming events</p>
<% end %>


<br><br><br>


<h3>Events You're Attending</h3>

<% if current_user.attended_events.any? %>
  <% current_user.attended_events.each do |event| %>
    <p><%= link_to event.title, event_path(event) %></p><br>
  <% end %>
<% else %>
  <p>You're not attending any events.</p>
<% end %>

app/views/sidebars/_events_show.html.erb
<% if current_user.id == @event.organizer.id %>
  <h3>This is Your Event</h3>
  <p class="sidebar_list"><%= link_to "edit event", edit_event_path(@event) %></p>
  <p><%= link_to("delete event", event_path(@event), method: :delete) %></p>
<% else %>
  <h3>Your Plans</h3>
  
  <div id="rsvp_status">
    <% if current_user.attended_events.include?(@event) %>
      <%= render "sidebars/show_rsvp_attending" %>
    <% else %>
      <%= render "sidebars/show_rsvp_button" %>
    <% end %>
  </div>


<% end %>


<br><br><br>


<h3>Who's Attending</h3>

<% if @event.participants.any? %>
  <% @event.participants.each do |participant| %>
    <p><%= link_to "@#{participant.twitter_handle}", "http://twitter.com/#{participant.twitter_handle}" %></p>
  <% end %>
<% else %>
  <p id="no_one">No one has signed up to attend this event.</p>
<% end %>

app/views/sidebars/_no_current_user.html.erb
<p>Sign in with twitter to begin event crafting.</p>
<br>
<a href="/sign_in"><div id= "signin_button" class="button center">sign in with twitter</div></a>

app/views/sidebars/_show_rsvp_attending.html.erb
<p>You're attending this event.</p>

app/views/sidebars/_show_rsvp_button.html.erb
<p>Let @<%= @event.organizer.twitter_handle %> know that you'll be there.</p>
<br><br>
<div id= "rsvp_button" class="button center">rsvp</div>